server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name app.heimdall-logtech.com;

    ssl_certificate     /etc/letsencrypt/live/app.heimdall-logtech.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.heimdall-logtech.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://heimdall-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
