server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name heimdall-logtech.com www.heimdall-logtech.com;

    ssl_certificate     /etc/letsencrypt/live/heimdall-logtech.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/heimdall-logtech.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /robots.txt { }
    location = /sitemap.xml { }
}
