version = 5.7.0
archive_dir = /etc/letsencrypt/archive/motorista.heimdall-logtech.com
cert = /etc/letsencrypt/live/motorista.heimdall-logtech.com/cert.pem
privkey = /etc/letsencrypt/live/motorista.heimdall-logtech.com/privkey.pem
chain = /etc/letsencrypt/live/motorista.heimdall-logtech.com/chain.pem
fullchain = /etc/letsencrypt/live/motorista.heimdall-logtech.com/fullchain.pem
[renewalparams]
account = 288468f49038f65bf3f6be6a6e77a38e
pref_challs = dns-01,
authenticator = manual
manual_auth_hook = /auth-hook.sh
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
