"""add delivery status tracking to message_logs

Revision ID: 0d566ff3001e
Revises: 3cdaaf58ca15
Create Date: 2026-07-07 16:01:54.193633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d566ff3001e'
down_revision: Union[str, None] = '3cdaaf58ca15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_logs', sa.Column('delivery_status', sa.String(length=20), nullable=True))
    op.add_column('message_logs', sa.Column('delivery_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_logs', 'delivery_updated_at')
    op.drop_column('message_logs', 'delivery_status')
    # ### end Alembic commands ###
