"""add is_tenant_admin to users

Revision ID: 3cdaaf58ca15
Revises: 83aa7174459c
Create Date: 2026-07-06 12:17:59.409364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdaaf58ca15'
down_revision: Union[str, None] = '83aa7174459c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_tenant_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_tenant_admin')
    # ### end Alembic commands ###
