"""add archived_at to occurrences

Revision ID: 83aa7174459c
Revises: d446218c48f6
Create Date: 2026-07-05 18:51:45.514632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83aa7174459c'
down_revision: Union[str, None] = 'd446218c48f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occurrences', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occurrences', 'archived_at')
    # ### end Alembic commands ###
