"""add driver_followup_acked to occurrences

Revision ID: 21f1992619a0
Revises: 0d566ff3001e
Create Date: 2026-07-07 17:58:52.629646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f1992619a0'
down_revision: Union[str, None] = '0d566ff3001e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occurrences', sa.Column('driver_followup_acked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occurrences', 'driver_followup_acked')
    # ### end Alembic commands ###
