"""add drivers table and occurrences driver_id

Revision ID: 233691e8df81
Revises: 21f1992619a0
Create Date: 2026-07-08 11:52:06.713022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233691e8df81'
down_revision: Union[str, None] = '21f1992619a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_drivers_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_drivers_tenant_id_phone')
    )
    op.create_index('ix_drivers_tenant_id', 'drivers', ['tenant_id'], unique=False)
    op.create_table('route_manifests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('route_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_route_manifests_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_route_manifests_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_manifests'))
    )
    op.create_index('ix_route_manifests_tenant_id', 'route_manifests', ['tenant_id'], unique=False)
    op.create_table('route_manifest_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('manifest_id', sa.UUID(), nullable=False),
    sa.Column('stop_number', sa.Integer(), nullable=False),
    sa.Column('driver_phone', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('route_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['manifest_id'], ['route_manifests.id'], name=op.f('fk_route_manifest_entries_manifest_id_route_manifests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_manifest_entries'))
    )
    op.create_index('ix_route_manifest_entries_driver_phone_stop', 'route_manifest_entries', ['manifest_id', 'driver_phone', 'stop_number'], unique=False)
    op.create_index('ix_route_manifest_entries_manifest_id', 'route_manifest_entries', ['manifest_id'], unique=False)
    op.add_column('occurrences', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_occurrences_driver_id_drivers'), 'occurrences', 'drivers', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_occurrences_driver_id_drivers'), 'occurrences', type_='foreignkey')
    op.drop_column('occurrences', 'driver_id')
    op.drop_index('ix_route_manifest_entries_manifest_id', table_name='route_manifest_entries')
    op.drop_index('ix_route_manifest_entries_driver_phone_stop', table_name='route_manifest_entries')
    op.drop_table('route_manifest_entries')
    op.drop_index('ix_route_manifests_tenant_id', table_name='route_manifests')
    op.drop_table('route_manifests')
    op.drop_index('ix_drivers_tenant_id', table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
